name: AWS Auth
description: Configure AWS credentials and login to AWS ECR

outputs:
  registry:
    description: "Registry"
    value: ${{ steps.login-ecr.outputs.registry }}

runs:
  using: composite

  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: "arn:aws:iam::${{env.AWS_ACCOUNT}}:role/GitHubAction-AssumeRoleWithActionForDevopsGirls2023"
        aws-region: ${{ env.AWS_REGION }}
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
