name: hello ops girls pipeline
run-name: build and test dev image
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build-and-test-dev-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unit test
        run: auto/test
